/* Provenance Ledger style: company story as an editorial dossier with ink navy structure, saffron route markers, and calm reveal motion. */
import { motion } from "framer-motion";
import { ArrowUpRight, Check, Globe2, MapPin, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useScrollReveal } from "@/hooks/useScrollReveal";
import SiteHeader from "@/components/SiteHeader";

const logoUrl = "/assets/cba-logo.png";
const heroUrl = "/assets/cba-hero-ingredients.webp";

export default function About() {
  useScrollReveal();
  return <div className="site-shell"><div className="top-strip"><div className="top-strip-inner"><span>Saudi-based supply partner</span><span className="top-strip-dot" /><span>Food ingredients & raw materials</span><a href="mailto:mohammed@cbaingredients.com">mohammed@cbaingredients.com</a></div></div><SiteHeader variant="inner" active="about" /><main>
    <section className="inner-hero"><div className="inner-hero-copy reveal"><div className="hero-kicker"><span className="pulse-dot" /> ABOUT CBA INGREDIENTS</div><h1>A clearer way<br /><em>to source.</em></h1><p>We are a Saudi-based company built around a simple idea: food businesses should be able to find the right ingredients, communicate clearly, and count on supply that keeps moving.</p><div className="hero-proof"><div className="proof-mark"><MapPin size={17} /></div><div><strong>Dammam, Saudi Arabia.</strong><span>Serving the Kingdom with a wider view.</span></div></div></div><div className="inner-hero-image reveal reveal-2"><img src={heroUrl} alt="Food ingredients arranged for formulation" /><div className="image-caption">CBA / 2026<br />A local partner with a global outlook</div></div></section>
    <section className="about-story section-pad"><div className="story-index"><span className="section-label"><span className="label-line" />01 / OUR STORY</span><span className="aside-number">A</span></div><div className="story-copy"><h2>Closer to the<br /><em>real work.</em></h2><p className="lead-copy">CBA Ingredients serves the people behind the products: the procurement team planning next month, the formulator solving a texture issue, and the operator who simply needs dependable stock.</p><p>Our portfolio brings together functional ingredients, essential raw materials, flavours, colours, powders, blends, and application-led solutions for a broad range of food businesses. We focus on the Saudi market because proximity matters — to customers, to delivery realities, and to the way food is made here.</p><p>That focus gives us a practical perspective. We are not interested in making sourcing feel complicated. We want to make it more transparent, more responsive, and more useful to the businesses we work with.</p></div><div className="story-aside"><div className="story-aside-line" /><p>“A better supply relationship starts with understanding what the customer is trying to achieve.”</p><small>CBA Ingredients / Our point of view</small></div></section>
    <section className="audience-section"><div className="section-pad"><div className="audience-head"><div><span className="section-label"><span className="label-line" />02 / WHO WE SERVE</span><h2>Built for the<br /><em>people who make.</em></h2></div><p>From established operations to ambitious new concepts, CBA helps teams source with confidence and keep their standards high.</p></div><div className="audience-grid">{["Dairy & ice cream producers", "Restaurant groups & cafés", "Bakeries & confectioners", "Caterers & food service", "Beverage makers", "Food manufacturers"].map((item, i) => <motion.div key={item} className="audience-item" initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06, duration: .35 }}><span>0{i + 1}</span><p>{item}</p><ArrowUpRight size={17} /></motion.div>)}</div></div></section>
    <section className="about-values section-pad"><span className="section-label"><span className="label-line" />03 / WHAT WE BELIEVE</span><div className="values-layout"><div><h2>Practical<br /><em>by design.</em></h2><p>Our difference is not a louder promise. It is the discipline of doing the useful things well, every day.</p></div><div className="values-list">{[{icon: Globe2, title: "Local context, global standard", copy: "Saudi market focus with a portfolio shaped by the quality and consistency modern food businesses expect."}, {icon: Sparkles, title: "Straightforward conversations", copy: "Clear answers, realistic timelines, and a direct line to the person helping you move forward."}, {icon: Check, title: "Value that holds up", copy: "Competitive thinking paired with dependable ingredients and a relationship built for repeat work."}].map((value, i) => <motion.div className="value-row" key={value.title} initial={{ opacity: 0, x: 14 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .08, duration: .35 }}><value.icon size={22} /><div><h3>{value.title}</h3><p>{value.copy}</p></div><span>0{i + 1}</span></motion.div>)}</div></div></section>
    <section className="page-cta section-pad"><div><span className="section-label"><span className="label-line" />NEXT / EXPLORE OUR APPROACH</span><h2>Supply is a<br /><em>shared ambition.</em></h2></div><Link className="button-primary" href="/sustainable-supply">See sustainable supply <ArrowUpRight size={17} /></Link></section>
  </main><Footer /></div>;
}

function Footer() { return <footer className="site-footer reveal"><div className="footer-brand"><img src={logoUrl} alt="CBA Ingredients" /><div><strong>CBA Ingredients</strong><span>Food ingredients & raw materials</span></div></div><div className="footer-links"><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/sustainable-supply">Sustainable supply</Link></div><div className="footer-note">© 2026 CBA Ingredients Company<br />Dammam, Saudi Arabia</div></footer>; }
