/* Provenance Ledger style: sustainable supply as a measured, editorial operating manifesto with no invented certifications or unverifiable claims. */
import { motion } from "framer-motion";
import { ArrowUpRight, Boxes, CircleCheck, Compass, Leaf, Link2, Recycle } from "lucide-react";
import { Link } from "wouter";
import { useScrollReveal } from "@/hooks/useScrollReveal";
import SiteHeader from "@/components/SiteHeader";

const logoUrl = "/assets/cba-logo.png";
const bakeryUrl = "/assets/cba-bakery-spices.webp";

export default function SustainableSupply() {
  useScrollReveal();
  return <div className="site-shell"><div className="top-strip"><div className="top-strip-inner"><span>Saudi-based supply partner</span><span className="top-strip-dot" /><span>Food ingredients & raw materials</span><a href="mailto:mohammed@cbaingredients.com">mohammed@cbaingredients.com</a></div></div><SiteHeader variant="inner" active="sustainable" /><main>
    <section className="sustain-hero"><div className="sustain-hero-copy reveal"><div className="hero-kicker"><span className="pulse-dot" /> SUSTAINABLE SUPPLY</div><h1>Move food<br /><em>forward.</em></h1><p>More responsible supply starts with the decisions made before an ingredient reaches the production line. We are building our approach around clarity, efficiency, and long-term value.</p><a className="button-primary" href="#principles">Explore our principles <ArrowUpRight size={17} /></a></div><div className="sustain-hero-side reveal reveal-2"><div className="sustain-number">03</div><div className="sustain-statement">A supply chain is not just a route between two points. It is a series of choices.</div><div className="sustain-line"><span /><span /><span /><span /></div></div></section>
    <section id="principles" className="sustain-intro section-pad"><div className="story-index"><span className="section-label"><span className="label-line" />01 / OUR RESPONSIBILITY</span><span className="aside-number">S</span></div><div className="story-copy"><h2>Progress is<br /><em>practical.</em></h2><p className="lead-copy">We believe responsible supply should be visible in the everyday details: how clearly we communicate, how thoughtfully we plan, and how carefully we protect product value.</p><p>As a Saudi-based distributor, our role is to create a more dependable connection between ingredient suppliers and the food businesses that rely on them. That means taking a long view of relationships, reducing avoidable friction, and treating every order as part of a wider operating system.</p></div><div className="sustain-photo"><img src={bakeryUrl} alt="Spices and grains arranged for food formulation" /><span>Small choices<br />compound over time.</span></div></section>
    <section className="principles-dark section-pad"><div className="principles-dark-head"><span className="section-label"><span className="label-line" />02 / THE WAY WE WORK</span><h2>Four signals<br /><em>of better supply.</em></h2></div><div className="sustain-principles">{[{icon: Compass, title: "Plan with context", text: "We listen to the application, production rhythm, and practical requirements behind each enquiry before recommending a route forward."}, {icon: Link2, title: "Strengthen relationships", text: "Long-term supplier and customer relationships make communication clearer and help quality expectations stay visible."}, {icon: Boxes, title: "Protect product value", text: "Careful handling, clear specifications, and disciplined coordination help ingredients arrive ready to do their job."}, {icon: Recycle, title: "Keep improving", text: "We look for useful improvements in planning and communication rather than making claims we cannot substantiate."}].map((item, i) => <motion.article className="sustain-principle" key={item.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07, duration: .4 }}><span className="principle-index">0{i + 1}</span><item.icon size={25} /><h3>{item.title}</h3><p>{item.text}</p></motion.article>)}</div></section>
    <section className="supply-loop section-pad"><div className="loop-copy"><span className="section-label"><span className="label-line" />03 / A BETTER LOOP</span><h2>From source<br /><em>to solution.</em></h2><p>Every ingredient has a story before it becomes part of yours. Our job is to make that journey simpler to understand and easier to trust.</p></div><div className="loop-diagram"><div className="loop-orbit" /><div className="loop-center"><Leaf size={25} /><span>CBA<br />INGREDIENTS</span></div>{[["01", "Source"], ["02", "Coordinate"], ["03", "Supply"], ["04", "Improve"]].map(([n, label], i) => <div className={`loop-node loop-node-${i + 1}`} key={n}><b>{n}</b><span>{label}</span></div>)}</div></section>
    <section className="page-cta section-pad"><div><span className="section-label"><span className="label-line" />NEXT / LET’S TALK</span><h2>Good supply<br /><em>starts simply.</em></h2></div><a className="button-primary" href="mailto:mohammed@cbaingredients.com?subject=Let%27s%20talk%20about%20supply">Contact Mohammed <ArrowUpRight size={17} /></a></section>
  </main><Footer /></div>;
}
function Footer() { return <footer className="site-footer"><div className="footer-brand"><img src={logoUrl} alt="CBA Ingredients" /><div><strong>CBA Ingredients</strong><span>Food ingredients & raw materials</span></div></div><div className="footer-links"><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/sustainable-supply">Sustainable supply</Link></div><div className="footer-note">© 2026 CBA Ingredients Company<br />Dammam, Saudi Arabia</div></footer>; }
